version: "3"
services:
  meilisync-admin:
    image: ghcr.io/long2ice/meilisync-admin/meilisync-admin
    restart: always
    network_mode: host
    environment:
      - DB_URL=mysql://root:msmiss6833@mysql:3306/meilisync_admin
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=2VItrow2zJCoWbdQPoMKU+pedKyivMqdWKQ1gIeIRrg=
      - SENTRY_DSN=
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: msmiss6833
      MYSQL_DATABASE: meilisync_admin
  redis:
    image: redis:latest
    restart: always
